# includes setuptools and wheel
FROM python:3.6-buster

#WORKDIR /usr/src/app

RUN apt-get update -y \
    && apt-get install -y python3-dev python3-pip build-essential \
    && apt-get install gcc -y \
    && apt-get install sudo -y \ 
    && apt-get clean

RUN pip3 install scrapy

RUN adduser --disabled-password --gecos '' airflow

USER airflow

# CMD ["--help"]
CMD ["python", "go_spider.py"]
#########################