# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster
#FROM apache/airflow:2.2.3

WORKDIR /app
#WORKDIR /opt/airflow/dags/tasks
#USER root

RUN apt-get update -y \
    && apt-get install -y python3-dev python3-pip build-essential \
    && apt-get install gcc -y \
    && apt-get install sudo -y \ 
    && apt-get clean

RUN pip3 install scrapy

#RUN adduser --disabled-password --gecos '' airflow

#USER airflow

COPY . .
#COPY --chown=airflow: . /opt/airflow/dags/tasks

#WORKDIR /opt/airflow/dags/tasks

# CMD ["--help"]
CMD ["python", "go_spider.py"]
#########################